const tintColor = '#2f95dc';

export default {
  primaryColor: '#932439',
  grey: '#746D75',
  tintColor,
  white: '#fff',
  black: 'rgba(0, 0, 0, 0.8)',
  mapMarkerColor: 'rgba(84,24,5,0.95)',
  mapsPolyline: '#6d99ec',
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  polygonStroke: '#a30909',
  polygonFill: 'rgba(163, 9, 9, 0.1)',
  markersPinColor: 'rgb(163, 9, 9)',
  shuttleBusMarkerPinColor: 'rgb(42,65,75)',
  searchBarPlaces: '#0041db',
};
